#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8000
#  application:
#    name: uiot-recive-msg
server:
  port: 8080
spring:
  application:
    name: uiot-receive-msg
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
